version: "3.8"

services:
  cicd_listener:
    build: .
    container_name: cicd_listener
    restart: unless-stopped
    ports:
      - "9000:9000"
    volumes:
      # Allow controlling host Docker from container
      - "/var/run/docker.sock:/var/run/docker.sock"

      # Mount deploy script
      - "/home/kraken/deploy-secret/vps-webhook-github/deploy_vps_sakamoto.sh:/app/deploy.sh:ro"

      # Optional: mount SSH key for GitHub access
      - "/home/kraken/.ssh:/root/.ssh:ro"
