version: "3.9"

services:
  webhook-listener:
    build:
      context: .            
      dockerfile: Dockerfile  
    container_name: webhook-listener
    ports:
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./hello-world:/app/hello-world
